name: deploytoservermaster
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
    - 'master'
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    - name: update the nuget  
      run: |
         cd C:\actions-runner\_work\_tool\nuget\latest\x64
         nuget restore C:\actions-runner\_work\dotnet-framework-docker\dotnet-framework-docker\samples\aspnetapp\aspnetapp.sln 
      shell: cmd
    - name: MSBuild
      run: |  
          cd C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\
          msbuild C:\actions-runner\_work\dotnet-framework-docker\dotnet-framework-docker\samples\aspnetapp\aspnetapp\aspnetapp.csproj /p:Configuration=Release -p:OutDir=c:\santhoshkumaar
      shell: cmd
