name: deploytoservermaster
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
    - 'master'
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    - name: Install NuGet client
      uses: warrenbuckley/Setup-Nuget@v1
    - name: update the nuget  
      run: nuget restore C:\actions-runner\actions-runner\dotnet-framework-docker\dotnet-framework-docker\samples\aspnetapp\aspnetapp.sln
    - name: MSBuild
      working-directory: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\
      run: MSBuild.exe C:\actions-runner\actions-runner\dotnet-framework-docker\dotnet-framework-docker\samples\aspnetapp\aspnetapp\aspnetapp.csproj -p:Configuration=Release /p:OutDir=c:\
      
